/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package housingapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandupa
 */
public class BuyingGUI extends javax.swing.JFrame {
    String owner;
    String type;
    String county;
    int bedrooms;
    int bathrooms;
    double fixed_price;
    double mortgage_price;
    int years;
    double total;
    
    Fixed f;
    ArrayList <Fixed> fList = new ArrayList();
    Mortgage m;
    ArrayList <Mortgage> mList = new ArrayList();

    /**
     * Creates new form BuyingGUI
     */
    public BuyingGUI() {
        initComponents();
        priceLbl.setVisible(false);
        priceTf.setVisible(false);
        yearsLbl.setVisible(false);
        yearsTf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ownerLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        countyLbl = new javax.swing.JLabel();
        bedroomLbl = new javax.swing.JLabel();
        bathroomLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        yearsLbl = new javax.swing.JLabel();
        ownerTf = new javax.swing.JTextField();
        bedroomTf = new javax.swing.JTextField();
        bathroomTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        yearsTf = new javax.swing.JTextField();
        countyCb = new javax.swing.JComboBox<>();
        fixedBtn = new javax.swing.JButton();
        mortgageBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        fviewBtn = new javax.swing.JButton();
        typeCb = new javax.swing.JComboBox<>();
        mviewBtn = new javax.swing.JButton();
        ownerLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(98, 0, 238));

        jLabel1.setFont(new java.awt.Font("Broadway", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUYING");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        ownerLbl.setForeground(new java.awt.Color(0, 0, 0));
        ownerLbl.setText("Owner:");

        typeLbl.setForeground(new java.awt.Color(0, 0, 0));
        typeLbl.setText("Type:");

        countyLbl.setForeground(new java.awt.Color(0, 0, 0));
        countyLbl.setText("County:");

        bedroomLbl.setForeground(new java.awt.Color(0, 0, 0));
        bedroomLbl.setText("Bedrooms:");

        bathroomLbl.setForeground(new java.awt.Color(0, 0, 0));
        bathroomLbl.setText("Bathrooms:");

        priceLbl.setForeground(new java.awt.Color(0, 0, 0));
        priceLbl.setText("Price:");

        yearsLbl.setForeground(new java.awt.Color(0, 0, 0));
        yearsLbl.setText("Years:");

        bathroomTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bathroomTfActionPerformed(evt);
            }
        });

        countyCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow" }));

        fixedBtn.setBackground(new java.awt.Color(187, 134, 252));
        fixedBtn.setForeground(new java.awt.Color(0, 0, 0));
        fixedBtn.setText("Fixed Price");
        fixedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedBtnActionPerformed(evt);
            }
        });

        mortgageBtn.setBackground(new java.awt.Color(187, 134, 252));
        mortgageBtn.setForeground(new java.awt.Color(0, 0, 0));
        mortgageBtn.setText("Mortgage");
        mortgageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mortgageBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(187, 134, 252));
        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("Add Record");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        fviewBtn.setBackground(new java.awt.Color(187, 134, 252));
        fviewBtn.setForeground(new java.awt.Color(0, 0, 0));
        fviewBtn.setText("View Record (F)");
        fviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fviewBtnActionPerformed(evt);
            }
        });

        typeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "House", "Apartment" }));

        mviewBtn.setBackground(new java.awt.Color(187, 134, 252));
        mviewBtn.setForeground(new java.awt.Color(0, 0, 0));
        mviewBtn.setText("View Record (M)");
        mviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mviewBtnActionPerformed(evt);
            }
        });

        ownerLbl1.setForeground(new java.awt.Color(0, 0, 0));
        ownerLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownerLbl1.setText("Choose an Option!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yearsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bathroomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bathroomTf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bedroomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bedroomTf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(countyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(countyCb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(typeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(typeCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ownerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ownerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fviewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fixedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mortgageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mviewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(ownerLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixedBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countyCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mortgageBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedroomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bedroomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bathroomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bathroomTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fviewBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mviewBtn))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bathroomTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bathroomTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bathroomTfActionPerformed

    private void fviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fviewBtnActionPerformed
        for(Fixed i:fList){
            if(i instanceof Fixed){
                JOptionPane.showMessageDialog(null, "Owner: " + i.getOwner() + "\n Type: " + i.getType() + "\n County: " + i.getCounty() + "\n Bedrooms: " + i.getBedrooms() + "\n Bathrooms: " + i.getBathrooms() + "\n Fixed Price: €" + ((Fixed) i).getFixed_price());
            }
        }
    }//GEN-LAST:event_fviewBtnActionPerformed

    private void fixedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedBtnActionPerformed
        priceLbl.setVisible(true);
        priceTf.setVisible(true);
        yearsLbl.setVisible(false);
        yearsTf.setVisible(false);        
        
        f = new Fixed();
    }//GEN-LAST:event_fixedBtnActionPerformed

    private void mortgageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mortgageBtnActionPerformed
        priceLbl.setVisible(true);
        priceTf.setVisible(true);
        yearsLbl.setVisible(true);
        yearsTf.setVisible(true);
        
        m = new Mortgage();
    }//GEN-LAST:event_mortgageBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(f instanceof Fixed){
            f = new Fixed();
            f.setOwner(ownerTf.getText());
            f.setType(typeCb.getSelectedItem().toString());
            f.setCounty(countyCb.getSelectedItem().toString());
            f.setBedrooms(Integer.parseInt(bedroomTf.getText()));
            f.setBathrooms(Integer.parseInt(bathroomTf.getText()));
            ((Fixed)f).setFixed_price(Double.parseDouble(priceTf.getText()));
            
            fList.add(f);
        }
        
        if(m instanceof Mortgage){
            m = new Mortgage();
            m.setOwner(ownerTf.getText());
            m.setType(typeCb.getSelectedItem().toString());
            m.setCounty(countyCb.getSelectedItem().toString());
            m.setBedrooms(Integer.parseInt(bedroomTf.getText()));
            m.setBathrooms(Integer.parseInt(bathroomTf.getText()));
            ((Mortgage)m).setMortgage_price(Double.parseDouble(priceTf.getText()));
            ((Mortgage)m).setYears(Integer.parseInt(yearsTf.getText()));
            
            m.compute();
            
            mList.add(m);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void mviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mviewBtnActionPerformed
        for(Mortgage i:mList){
            if(i instanceof Mortgage){
                JOptionPane.showMessageDialog(null, "Owner: " + i.getOwner() + "\n Type: " + i.getType() + "\n County: " + i.getCounty() + "\n Bedrooms: " + i.getBedrooms() + "\n Bathrooms: " + i.getBathrooms() + "\n Mortgage Price: €" + ((Mortgage) i).getTotal() + " Per Year");
            }
        }
    }//GEN-LAST:event_mviewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel bathroomLbl;
    private javax.swing.JTextField bathroomTf;
    private javax.swing.JLabel bedroomLbl;
    private javax.swing.JTextField bedroomTf;
    private javax.swing.JComboBox<String> countyCb;
    private javax.swing.JLabel countyLbl;
    private javax.swing.JButton fixedBtn;
    private javax.swing.JButton fviewBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mortgageBtn;
    private javax.swing.JButton mviewBtn;
    private javax.swing.JLabel ownerLbl;
    private javax.swing.JLabel ownerLbl1;
    private javax.swing.JTextField ownerTf;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTf;
    private javax.swing.JComboBox<String> typeCb;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JLabel yearsLbl;
    private javax.swing.JTextField yearsTf;
    // End of variables declaration//GEN-END:variables
}
