/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package housingapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x17114357
 */
public class RentingGUI extends javax.swing.JFrame {
ArrayList<Renting> rList;
int rCount;
    //String[] county = { "antrim","armagh","carlow","cavan","clare","cork","derry","donegal","down","dublin","fermanagh","galway","kerry","kildare","kilkenny","laois","leitrim","limerick","longford","louth","mayo","meath","monaghan","offaly","roscommon","sligo","tipperary","tyrone","waterford","westmeath","wexford","wicklow"};
  //  String[] type = { "Apartment","House","Studio","Flat" };
    String owner,county,type;

    /**
     * Creates new form RentingGUI
     */
    public RentingGUI() {
        initComponents();
        rList = new ArrayList<>();
        rCount=0;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Add = new javax.swing.JPanel();
        ownerTF = new javax.swing.JTextField();
        OwnerLbl = new javax.swing.JLabel();
        CountyLbl = new javax.swing.JLabel();
        RentComboBox = new javax.swing.JComboBox<>();
        bedroomsTF = new javax.swing.JTextField();
        BedroomsLbl = new javax.swing.JLabel();
        bathroomsTF = new javax.swing.JTextField();
        BathroomsLbl = new javax.swing.JLabel();
        Minimum_RentTF = new javax.swing.JTextField();
        Min_RentLbl = new javax.swing.JLabel();
        Max_RentLbl = new javax.swing.JLabel();
        Maximum_RentTF = new javax.swing.JTextField();
        ViewBtn = new javax.swing.JButton();
        Type = new javax.swing.JLabel();
        TypeComboBox = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        AffordibilityBtn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Renting Application");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        ownerTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerTFActionPerformed(evt);
            }
        });

        OwnerLbl.setText("Name of Owner");

        CountyLbl.setText("County");

        RentComboBox.setMaximumRowCount(20);
        RentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Antrim", "Armagh", "Carlow", "Cavan", "Clare", "Cork", "Derry", "Donegal", "Down", "Dublin", "Fermanagh", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Tyrone", "Waterford", "Westmeath", "Wexford", "Wicklow" }));
        RentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentComboBoxActionPerformed(evt);
            }
        });

        BedroomsLbl.setText("Bedrooms");

        BathroomsLbl.setText("Bathrooms");

        Min_RentLbl.setText("Minimum Rent");

        Max_RentLbl.setText("Maximum  Rent");

        ViewBtn.setText("Show Property");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        Type.setText("Type");

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartment", "House", "Studio", "Flat" }));
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });

        addBtn.setText("Add Property");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Remove Property");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        AffordibilityBtn.setText("Affordability");
        AffordibilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffordibilityBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AddLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Max_RentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Maximum_RentTF, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddLayout.createSequentialGroup()
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Min_RentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(AddLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CountyLbl)
                                                    .addComponent(BedroomsLbl)
                                                    .addComponent(BathroomsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(OwnerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Minimum_RentTF)
                                    .addComponent(bathroomsTF)
                                    .addComponent(bedroomsTF)
                                    .addComponent(ownerTF)
                                    .addComponent(RentComboBox, 0, 104, Short.MAX_VALUE)
                                    .addComponent(TypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AffordibilityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OwnerLbl)
                            .addComponent(ownerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CountyLbl)
                            .addComponent(RentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BedroomsLbl)
                            .addComponent(bedroomsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(AffordibilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BathroomsLbl))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bathroomsTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Minimum_RentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Min_RentLbl)))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Maximum_RentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Max_RentLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ownerTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerTFActionPerformed

    private void RentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentComboBoxActionPerformed
    String selectedValue = RentComboBox.getSelectedItem().toString();

        // TODO add your handling code here:
    }//GEN-LAST:event_RentComboBoxActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
String owner,county,bedrooms,bathrooms,type;
int min_rent,max_rent;
Renting r;
owner=ownerTF.getText();
bedrooms=bedroomsTF.getText();
bathrooms=bathroomsTF.getText();
min_rent=Integer.parseInt(Minimum_RentTF.getText());
max_rent=Integer.parseInt(Maximum_RentTF.getText());
county = RentComboBox.getSelectedItem().toString();
type=TypeComboBox.getSelectedItem().toString();

rCount=rList.size();
if(owner.equals("")||type.equals("")){
     JOptionPane.showMessageDialog(null, "You did not enter the owner name or county");

}
else {
for(int i=0;i<rCount;i++){
    r = rList.get(i);
   Renting rent = (Renting)r;
    JOptionPane.showMessageDialog(null, "owner "+rent.getOwner()+" bedrooms "+rent.getBedrooms()+" bathrooms "+rent.getBathrooms()+" county "+rent.getCounty()+" type "+rent.getType()+" maximum rent "+rent.getMax_rent()+" minimum rent "+rent.getMin_rent());


readFromFile();
}

}





        // TODO add your handling code here:
    }//GEN-LAST:event_ViewBtnActionPerformed
 public void writeToFile(){
String owner,county,bedrooms,bathrooms,type;
int min_rent,max_rent;
    try {
        File f =new File("renting.dat");
        FileOutputStream fStream =new FileOutputStream(f);
        ObjectOutputStream oStream=new ObjectOutputStream(fStream);
        oStream.writeObject(rList);
        oStream.close();
    }
    catch(IOException e){
   System.out.println(e);
    } 
 }
     public void readFromFile(){
        try{
            File f=new File("renting.dat");
            FileInputStream fStream= new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(fStream);
           rList = (ArrayList<Renting>) oStream.readObject();
           oStream.close();
            
        }
        catch(IOException|ClassNotFoundException e ){
                System.out.println(e);
        }
        
    
        }
 
    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
          String selectedValue = TypeComboBox.getSelectedItem().toString();

        // TODO add your handling code here:
    }//GEN-LAST:event_TypeComboBoxActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
String owner,county,type;
int min_rent,max_rent,bedrooms,bathrooms;
Renting r;
owner=ownerTF.getText();
bedrooms=Integer.parseInt(bedroomsTF.getText());
bathrooms=Integer.parseInt(bathroomsTF.getText());
min_rent=Integer.parseInt(Minimum_RentTF.getText());
max_rent=Integer.parseInt(Maximum_RentTF.getText());
county = RentComboBox.getSelectedItem().toString();
type=TypeComboBox.getSelectedItem().toString();

r = new Renting( min_rent, max_rent, owner,type, county,  bedrooms,  bathrooms);


rList.add(r);

writeToFile();
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
this.dispose();
new HousingGUI().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
      owner=ownerTF.getText();
      county=RentComboBox.getSelectedItem().toString();
      type=TypeComboBox.getSelectedItem().toString();
       Renting r;
       rCount=rList.size();
       
       if(owner.equals("")||county.equals("")||type.equals("")){
        JOptionPane.showMessageDialog(null, "Enter the owner and type of housing to delete  ");   
       }
       else {
           for(int i=0;i<rCount;i++){
              r=rList.get(i);
              
              if(owner.equals(r.getOwner())||county.equals(r.getCounty())){
                  rList.remove(i);
                  
              }
              
              JOptionPane.showMessageDialog(null,"The Owner and the apartment has been removed");
               
               writeToFile();
           }
       }
           
         
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void AffordibilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffordibilityBtnActionPerformed
        double rent,salary;
        Renting r = new Renting();

        salary= Double.parseDouble(JOptionPane.showInputDialog(null, "Enter your Annual Salary"));
        r.setSalary(salary);
        
        r.compute();
        
        JOptionPane.showMessageDialog(null, "The maximum affordable rent you can pay per month is = "+r.getRent());
        // TODO add your handling code here:
    }//GEN-LAST:event_AffordibilityBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JButton AffordibilityBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel BathroomsLbl;
    private javax.swing.JLabel BedroomsLbl;
    private javax.swing.JLabel CountyLbl;
    private javax.swing.JLabel Max_RentLbl;
    private javax.swing.JTextField Maximum_RentTF;
    private javax.swing.JLabel Min_RentLbl;
    private javax.swing.JTextField Minimum_RentTF;
    private javax.swing.JLabel OwnerLbl;
    private javax.swing.JComboBox<String> RentComboBox;
    private javax.swing.JLabel Type;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField bathroomsTF;
    private javax.swing.JTextField bedroomsTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ownerTF;
    // End of variables declaration//GEN-END:variables
}
